spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/corfiddb
    username: root
    password: 123
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update